
project_id = "evggwokrvotnnkazteia"

[functions.extract-skills]
verify_jwt = true

[functions.extract-minimum-skills]
verify_jwt = true

[functions.generate-video-questions]
verify_jwt = true

[functions.generate-screening-questions]
verify_jwt = true

[functions.generate-other-info]
verify_jwt = true
