
project_id = "evggwokrvotnnkazteia"

# This is a Supabase configuration file.
# It is used to configure the edge functions in your project.

[functions.google-auth]
verify_jwt = false

[functions.send-gmail]
verify_jwt = false
