
project_id = "evggwokrvotnnkazteiat"

# This is a Supabase configuration file.
# It is used to configure the edge functions in your project.

[functions.google-auth]
verify_jwt = false

[functions.send-gmail]
verify_jwt = false

[functions.extract-skills]
verify_jwt = false

[functions.generate-video-questions]
verify_jwt = false

[functions.generate-screening-questions]
verify_jwt = false

[functions.generate-other-info]
verify_jwt = false
