
project_id = "evggwokrvotnnkazteia"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = true

[auth.external.github]
enabled = true
client_id = "env(SUPABASE_GITHUB_CLIENT_ID)"
secret = "env(SUPABASE_GITHUB_SECRET)"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_GOOGLE_SECRET)"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[experimental]
tracing = false

[functions.generate-video-questions]
verify_jwt = true

[functions.generate-screening-questions]
verify_jwt = true

[functions.extract-skills]
verify_jwt = true

[functions.extract-minimum-skills]
verify_jwt = true

[functions.generate-other-info]
verify_jwt = true

[functions.create-default-prompts]
verify_jwt = true
