
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evggwokrvotnnkazteia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2Z2d3b2tydm90bm5rYXp0ZWlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTMyNTIsImV4cCI6MjA1OTM2OTI1Mn0.b3XyJW0ncyDzSSJ_377GTQQ3IOIUolo4sblFWWp28ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
